version: '3'

services:

  company_srv:
    restart: always
    build:
      context: .
      dockerfile: ./company/Dockerfile
    container_name: company_srv
    ports:
      - 3000:3000
    depends_on:
      - mongo

  product_srv:
    restart: always
    build:
      context: .
      dockerfile: ./product/Dockerfile
    container_name: product_srv
    ports:
      - 3001:3001
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - /data:/data/db
